/*
 */
package GUI;

import civitas.Casilla;

/**
 *
 * @author gonzalo
 */
public class CasillaPanel extends javax.swing.JPanel {

    Casilla casilla;
    
    /**
     * Creates new form Casilla
     */
    public CasillaPanel() {
        initComponents();
    }
    
    void setCasilla(Casilla casilla){
        this.casilla = casilla;
        nombreTex.setText(casilla.getNombre());
        compraTex.setText(Float.toString(casilla.getPrecioCompra()));
        edificarTex.setText(Float.toString(casilla.getPrecioEdificar()));
        alquilerTex.setText(Float.toString(casilla.getPrecioAlquilerCompleto()));
        
        repaint();
        revalidate();
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreEtiq = new javax.swing.JLabel();
        nombreTex = new javax.swing.JTextField();
        compraTex = new javax.swing.JTextField();
        edificarTex = new javax.swing.JTextField();
        alquilerTex = new javax.swing.JTextField();
        compraEtiq = new javax.swing.JLabel();
        edificarEtiq = new javax.swing.JLabel();
        alquilerEtiq = new javax.swing.JLabel();
        tituloPanel = new javax.swing.JLabel();

        nombreEtiq.setText("Nombre");

        nombreTex.setEditable(false);
        nombreTex.setText("jTextField1");

        compraTex.setEditable(false);
        compraTex.setText("jTextField2");

        edificarTex.setEditable(false);
        edificarTex.setText("jTextField3");

        alquilerTex.setEditable(false);
        alquilerTex.setText("jTextField4");

        compraEtiq.setText("Precio compra");

        edificarEtiq.setText("Precio edificar");

        alquilerEtiq.setText("Precio alquiler");

        tituloPanel.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        tituloPanel.setText("Casilla actual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreEtiq)
                            .addComponent(compraEtiq)
                            .addComponent(edificarEtiq)
                            .addComponent(alquilerEtiq))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compraTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edificarTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alquilerTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(tituloPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreEtiq)
                            .addComponent(nombreTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(compraTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compraEtiq))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edificarTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edificarEtiq))
                        .addGap(18, 18, 18)
                        .addComponent(alquilerTex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alquilerEtiq))
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alquilerEtiq;
    private javax.swing.JTextField alquilerTex;
    private javax.swing.JLabel compraEtiq;
    private javax.swing.JTextField compraTex;
    private javax.swing.JLabel edificarEtiq;
    private javax.swing.JTextField edificarTex;
    private javax.swing.JLabel nombreEtiq;
    private javax.swing.JTextField nombreTex;
    private javax.swing.JLabel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
