/*
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import javax.swing.JOptionPane;

public class CivitasView extends javax.swing.JFrame implements Vista {

    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        rankingTex.setVisible(false);
        rankingEtiq.setVisible(false);        
    }
    
    CivitasJuego juego;
    
    void setCivitasJuego(CivitasJuego juego){
        this.juego = juego;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJuego = new javax.swing.JLabel();
        casilla1 = new GUI.CasillaPanel();
        operacionEtiq = new javax.swing.JLabel();
        operacionTex = new javax.swing.JTextField();
        rankingEtiq = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jugadorPanel2 = new GUI.JugadorPanel();
        rankingTex = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloJuego.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        tituloJuego.setText("Civitas, El Juego");

        operacionEtiq.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        operacionEtiq.setText("Siguiente operación");

        operacionTex.setEditable(false);
        operacionTex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacionTexActionPerformed(evt);
            }
        });

        rankingEtiq.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        rankingEtiq.setText("Ranking");

        rankingTex.setEditable(false);
        rankingTex.setColumns(20);
        rankingTex.setRows(5);
        rankingTex.setAutoscrolls(false);
        rankingTex.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugadorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloJuego)
                    .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(rankingTex, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rankingEtiq)
                            .addComponent(operacionTex, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(operacionEtiq))))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugadorPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operacionEtiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(operacionTex, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rankingEtiq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rankingTex, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operacionTexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacionTexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operacionTexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.CasillaPanel casilla1;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorPanel2;
    private javax.swing.JLabel operacionEtiq;
    private javax.swing.JTextField operacionTex;
    private javax.swing.JLabel rankingEtiq;
    private javax.swing.JTextArea rankingTex;
    private javax.swing.JLabel tituloJuego;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualiza() {
        jugadorPanel2.setJugador(juego.getJugadorActual());
        int casillaActual = juego.getJugadorActual().getCasillaActual();
        casilla1.setCasilla(juego.getTablero().getCasilla(casillaActual));
        
        if (juego.finalDelJuego()){
            rankingTex.setText(juego.mostrarRanking());
            rankingTex.setVisible(true);
            rankingEtiq.setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    @Override
    public void pausa() {
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
            "Siguiente paso", JOptionPane.YES_NO_OPTION);
        
        if (val==1) System.exit(0);
    }

    @Override
    public Respuesta comprar() {
        Respuesta res;
        int opcion= 1-JOptionPane.showConfirmDialog(null, ""
                + "¿Quieres comprar la calle actual?", "Compra", 
                JOptionPane.YES_NO_OPTION);
        
        if (opcion == 0)
            res = Respuesta.NO;
        else
            res = Respuesta.SI;
        
        return res;
    }

    @Override
    public OperacionInmobiliaria elegirOperacion() {
        OperacionInmobiliaria op = null;
        GestionarDialog gestionarD = new GestionarDialog(this);
        int opt = gestionarD.getGestion();
        
        switch (opt){
            case 0:
                op = OperacionInmobiliaria.CONSTRUIR_CASA;
                break;
            case 1:
                op = OperacionInmobiliaria.CONSTRUIR_HOTEL;
                break;
            case 2:
                op = OperacionInmobiliaria.TERMINAR;
                break;
        }
        return op;
    }

    @Override
    public int elegirPropiedad() {
        PropiedadDialog propiedadD = new PropiedadDialog(this, 
                juego.getJugadorActual());
        int id = propiedadD.getPropiedad();
        
        return id;
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion) {
        operacionTex.setText(juego.siguientePaso().toString());
        
        if (operacion == OperacionJuego.AVANZAR)
            Dado.createInstance(this);
        
        repaint();
        revalidate();
    }

    @Override
    public void mostrarEventos() {
        if (!Diario.getInstance().getEventos().isEmpty()){
            //crea la ventana del diario
            DiarioDialog diarioD= new DiarioDialog(this);
        }
    }
}
