/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.util.ArrayList;
import modelo.Modelo;


public class VistaPrincipal extends javax.swing.JFrame implements Vista {

    Controlador controlador;
    
    public VistaPrincipal() {
        initComponents();
        
        this.setVisible(true);
    }
    
    public void setControlador(Controlador c) {
        controlador=c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaColeccion = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        botonAñade = new javax.swing.JButton();
        botonQuita = new javax.swing.JButton();
        añadeVarios = new javax.swing.JButton();
        cantidadVeces = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistaColeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        numero.setText("0");

        botonAñade.setText("Añade");
        botonAñade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadeActionPerformed(evt);
            }
        });

        botonQuita.setText("Quita");
        botonQuita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitaActionPerformed(evt);
            }
        });

        añadeVarios.setText("Añade:");
        añadeVarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadeVariosActionPerformed(evt);
            }
        });

        cantidadVeces.setText("0");
        cantidadVeces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadVecesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vistaColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonQuita)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonAñade)
                                .addGap(36, 36, 36)
                                .addComponent(añadeVarios)
                                .addGap(27, 27, 27)
                                .addComponent(cantidadVeces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(vistaColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAñade)
                    .addComponent(añadeVarios)
                    .addComponent(cantidadVeces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(botonQuita)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadeActionPerformed
        Integer i=Integer.parseInt(this.numero.getText());
        controlador.añadeElemento(i);
    }//GEN-LAST:event_botonAñadeActionPerformed

    private void botonQuitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitaActionPerformed
        controlador.quitaUno();
    }//GEN-LAST:event_botonQuitaActionPerformed

    private void añadeVariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadeVariosActionPerformed
        Integer valor = Integer.parseInt(this.numero.getText());
        Integer cantidad = Integer.parseInt(this.cantidadVeces.getText());
        controlador.añadeVariosElementos(valor, cantidad);

    }//GEN-LAST:event_añadeVariosActionPerformed

    private void cantidadVecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadVecesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadVecesActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void recibeModelo(Modelo m) {
        
        ArrayList<Integer> coleccion=m.getColeccion1();
        
        this.vistaColeccion.removeAll();
        for(Integer i:coleccion) {
            VistaElemento ve=new VistaElemento();
            ve.recibeModelo(i);
            this.vistaColeccion.add(ve);
        }
        repaint();
        revalidate();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadeVarios;
    private javax.swing.JButton botonAñade;
    private javax.swing.JButton botonQuita;
    private javax.swing.JTextField cantidadVeces;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel vistaColeccion;
    // End of variables declaration//GEN-END:variables
}
